### ISSUE TITLE
Build/install problems (autogen?)

### ISSUE THREAD

**Issue by GameboyRMH** [deters/mygestures#5]
Long-time user here, unfortunately the latest version doesn't build. Autogen appears to complete successfully on Mint 17.2:

`Preparing the MyGestures build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.14.1
Found GNU Libtool version 2.4.2

Automatically preparing build ... done

The MyGestures build system is now prepared.  To build here, run:
  ./configure
  make
`
Following instructions, next I run make:

`make: *** No targets specified and no makefile found.  Stop.
`

If I attempt ./configure first, it runs with no errors, then attempt make again:

`Making all in src
make[1]: Entering directory `/home/gameboyrmh/mygestures/src'
make  all-am
make[2]: Entering directory `/home/gameboyrmh/mygestures/src'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2    -g -O2 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo mygestures.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2    -g -O2 -MT mygestures.o -MD -MP -MF $depbase.Tpo -c -o mygestures.o mygestures.c &&\
	mv -f $depbase.Tpo $depbase.Po
mygestures.c: In function 'mygestures_run':
mygestures.c:152:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < self->device_count; ++i) {
   ^
mygestures.c:152:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [mygestures.o] Error 1
make[2]: Leaving directory `/home/gameboyrmh/mygestures/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/gameboyrmh/mygestures/src'
make: *** [all-recursive] Error 1
`

**Comment by deters** [comment]
You can try:

make clean ; sh autogenerated.sh; make;


Or try to clone the repo again


sudo apt install pkg-config autoconf libtool libx11-dev libxrender-dev
libxtst-dev libxml2-dev git
git clone https://github.com/deters/mygestures.git
cd mygestures/
sh autogen.sh
make
sudo make install



Em sáb, 9 de mar de 2019 12:39, GameboyRMH <notifications@github.com>
escreveu:

**Comment by deters** [comment]
Correct command:

sh autogen

My Android keyboard autocorrected to autogenerated.sh

Em sáb, 9 de mar de 2019 14:37, Lucas Deters <lucasdeters@gmail.com>
escreveu:

**Comment by GameboyRMH** [comment]
Hmm no luck with that, prerequesite packages were installed, I ran a fresh git clone, if I try "make clean" after autogen.sh I get:

`make: *** No rule to make target `clean'.  Stop.`

If I run it after ./configure I get:

`Making clean in src
make[1]: Entering directory `/home/gameboyrmh/mygestures/src'
test -z "mygestures" || rm -f mygestures
rm -f *.o
rm -f drawing/*.o
make[1]: Leaving directory `/home/gameboyrmh/mygestures/src'
make[1]: Entering directory `/home/gameboyrmh/mygestures'
make[1]: Nothing to be done for `clean-am'.
make[1]: Leaving directory `/home/gameboyrmh/mygestures'
`
And the make command fails with the same errors.

**Comment by deters** [comment]
Try running:
automake



Em sáb, 9 de mar de 2019 14:50, GameboyRMH <notifications@github.com>
escreveu:

**Comment by GameboyRMH** [comment]
automake doesn't produce any output, automake -v shows:

`automake: thread 0: reading autoconf --trace=_AM_COND_IF:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_FILES:\$f:\$l::\$d::\$n::\${::}% --trace=AM_AUTOMAKE_VERSION:\$f:\$l::\$d::\$n::\${::}% --trace=AM_PROG_AR:\$f:\$l::\$d::\$n::\${::}% --trace=AM_EXTRA_RECURSIVE_TARGETS:\$f:\$l::\$d::\$n::\${::}% --trace=AC_REQUIRE_AUX_FILE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_INIT:\$f:\$l::\$d::\$n::\${::}% --trace=m4_sinclude:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_AUX_DIR:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_BUILD:\$f:\$l::\$d::\$n::\${::}% --trace=AM_GNU_GETTEXT:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_TARGET:\$f:\$l::\$d::\$n::\${::}% --trace=_LT_AC_TAGCONFIG:\$f:\$l::\$d::\$n::\${::}% --trace=AC_FC_SRCEXT:\$f:\$l::\$d::\$n::\${::}% --trace=AM_INIT_AUTOMAKE:\$f:\$l::\$d::\$n::\${::}% --trace=AM_PROG_MKDIR_P:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_LINKS:\$f:\$l::\$d::\$n::\${::}% --trace=AC_SUBST_TRACE:\$f:\$l::\$d::\$n::\${::}% --trace=AM_GNU_GETTEXT_INTL_SUBDIR:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_COND_ELSE:\$f:\$l::\$d::\$n::\${::}% --trace=m4_include:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_COND_ENDIF:\$f:\$l::\$d::\$n::\${::}% --trace=_AM_SUBST_NOTMAKE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_LIBSOURCE:\$f:\$l::\$d::\$n::\${::}% --trace=AM_CONDITIONAL:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_LIBOBJ_DIR:\$f:\$l::\$d::\$n::\${::}% --trace=LT_SUPPORTED_TAG:\$f:\$l::\$d::\$n::\${::}% --trace=sinclude:\$f:\$l::\$d::\$n::\${::}% --trace=AM_MAINTAINER_MODE:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CONFIG_HEADERS:\$f:\$l::\$d::\$n::\${::}% --trace=AC_CANONICAL_HOST:\$f:\$l::\$d::\$n::\${::}%
automake: thread 0: reading /usr/share/automake-1.14/am/header-vars.am
automake: thread 0: reading Makefile.am
automake: thread 0: reading /usr/share/automake-1.14/am/configure.am
automake: thread 0: reading /usr/share/automake-1.14/am/texinfos.am
automake: thread 0: reading /usr/share/automake-1.14/am/data.am
automake: thread 0: reading /usr/share/automake-1.14/am/inst-vars.am
automake: thread 0: reading /usr/share/automake-1.14/am/subdirs.am
automake: thread 0: reading /usr/share/automake-1.14/am/tags.am
automake: thread 0: reading /usr/share/automake-1.14/am/distdir.am
automake: thread 0: reading /usr/share/automake-1.14/am/footer.am
automake: thread 0: reading /usr/share/automake-1.14/am/install.am
automake: thread 0: reading /usr/share/automake-1.14/am/clean.am
automake: thread 0: creating Makefile.in
automake: thread 0: reading src/Makefile.am
automake: thread 0: reading /usr/share/automake-1.14/am/remake-hdr.am
automake: thread 0: reading /usr/share/automake-1.14/am/clean-hdr.am
automake: thread 0: reading /usr/share/automake-1.14/am/progs.am
automake: thread 0: reading /usr/share/automake-1.14/am/program.am
automake: thread 0: reading /usr/share/automake-1.14/am/compile.am
automake: thread 0: reading /usr/share/automake-1.14/am/depend.am
automake: thread 0: reading /usr/share/automake-1.14/am/depend2.am
automake: thread 0: Sources ending in .c become .o
automake: thread 0: Sources ending in .c become .obj
automake: thread 0: reading /usr/share/automake-1.14/am/lang-compile.am
automake: thread 0: creating src/Makefile.in
`
No change to the output of make or make install after running this.

**Comment by deters** [comment]
I can't help you right now since my notebook power adaptor died today...
I'll take a look as soon as have access to a computer...

Em sáb, 9 de mar de 2019 15:06, GameboyRMH <notifications@github.com>
escreveu:

**Comment by deters** [comment]
Hi, sorry I had an issue with my notebook at the time. Do you still need help?

**Comment by GameboyRMH** [comment]
I'm now running Mint 19.3 but I have the same problems when trying to compile the latest version. I've been running mygestures v1.3 as a workaround.

**Comment by deters** [comment]
Can you paste this in a new terminal and send me all the outputs?

rm -Rf /tmp/mygestures
cd /tmp
git clone https://github.com/deters/mygestures.git
cd mygestures/
sh autogen.sh
./configure
make

**Comment by GameboyRMH** [comment]
Worked this time! I now have mygestures v3.0 installed and working. The difference from my previous attempt on Mint 19.3 a few minutes ago was running ./configure before the make command, I suppose that should be added to README.md? I notice it is in the autogen.sh output but I'd missed that on the previous attempt.

`gameboyrmh@laptop1 /tmp $ rm -Rf /tmp/mygestures
gameboyrmh@laptop1 /tmp $ cd /tmp
gameboyrmh@laptop1 /tmp $ git clone https://github.com/deters/mygestures.git
Cloning into 'mygestures'...
remote: Enumerating objects: 352, done.
remote: Counting objects: 100% (352/352), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 1654 (delta 254), reused 294 (delta 202), pack-reused 1302
Receiving objects: 100% (1654/1654), 622.80 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (1185/1185), done.
gameboyrmh@laptop1 /tmp $ cd mygestures/
gameboyrmh@laptop1 /tmp/mygestures $ sh autogen.sh
Preparing the MyGestures build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.15.1
Found GNU Libtool version 2.4.6

Automatically preparing build ... done

The MyGestures build system is now prepared.  To build here, run:
  ./configure
  make
gameboyrmh@laptop1 /tmp/mygestures $ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for X11... yes
checking for Xrender... yes
checking for Xtst... yes
checking for Xi... yes
checking for libXML... yes
checking for library containing shm_open... -lrt
checking how to run the C preprocessor... gcc -E
checking for X... libraries , headers 
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for unistd.h... (cached) yes
checking for mode_t... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for bzero... yes
checking for memset... yes
checking for mkdir... yes
checking for regcomp... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strncasecmp... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands
gameboyrmh@laptop1 /tmp/mygestures $ make
Making all in src
make[1]: Entering directory '/tmp/mygestures/src'
make  all-am
make[2]: Entering directory '/tmp/mygestures/src'
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo mygestures.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT mygestures.o -MD -MP -MF $depbase.Tpo -c -o mygestures.o mygestures.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo configuration.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT configuration.o -MD -MP -MF $depbase.Tpo -c -o configuration.o configuration.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo configuration_parser.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT configuration_parser.o -MD -MP -MF $depbase.Tpo -c -o configuration_parser.o configuration_parser.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo actions.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT actions.o -MD -MP -MF $depbase.Tpo -c -o actions.o actions.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo grabbing.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT grabbing.o -MD -MP -MF $depbase.Tpo -c -o grabbing.o grabbing.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo grabbing-synaptics.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT grabbing-synaptics.o -MD -MP -MF $depbase.Tpo -c -o grabbing-synaptics.o grabbing-synaptics.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo drawing/drawing-backing.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT drawing/drawing-backing.o -MD -MP -MF $depbase.Tpo -c -o drawing/drawing-backing.o drawing/drawing-backing.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo drawing/drawing-brush.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT drawing/drawing-brush.o -MD -MP -MF $depbase.Tpo -c -o drawing/drawing-brush.o drawing/drawing-brush.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo drawing/drawing-brush-image.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT drawing/drawing-brush-image.o -MD -MP -MF $depbase.Tpo -c -o drawing/drawing-brush-image.o drawing/drawing-brush-image.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo drawing/drawing-bresenham.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.    -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2 -MT drawing/drawing-bresenham.o -MD -MP -MF $depbase.Tpo -c -o drawing/drawing-bresenham.o drawing/drawing-bresenham.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc -DSYSCONFDIR='"/usr/local/etc"' -O2 -I/usr/include/libxml2  -g -O2   -o mygestures main.o mygestures.o configuration.o configuration_parser.o actions.o grabbing.o grabbing-synaptics.o drawing/drawing-backing.o drawing/drawing-brush.o drawing/drawing-brush-image.o drawing/drawing-bresenham.o -lxml2 -lX11 -lXrender -lX11 -lXtst -lxml2 -lXi -lm -lrt 
make[2]: Leaving directory '/tmp/mygestures/src'
make[1]: Leaving directory '/tmp/mygestures/src'
make[1]: Entering directory '/tmp/mygestures'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/tmp/mygestures'
`

**Comment by deters** [comment]
Sorry about that, I just fixed the readme. 

Also, as a good news, I'm working on a new version of mygestures, to be released very soon.

**Comment by GameboyRMH** [comment]
Great, keep up the good work!
